### ISSUE TITLE
Eclipse importer fails for MoDisco

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#14]
When trying to import the MoDisco project from its URL (https://projects.eclipse.org/projects/modeling.mdt.modisco), the following exception is thrown:

``` java
java.lang.NullPointerException
ERROR [importer.eclipse ] (14:53:41): Unable to import modeling.mdt.modiscoproject.
    at org.ossmeter.repository.model.eclipse.importer.EclipseProjectImporter.getPlatforms(EclipseProjectImporter.java:896)
    at org.ossmeter.repository.model.eclipse.importer.EclipseProjectImporter.importProject(EclipseProjectImporter.java:214)
    at org.ossmeter.platform.client.api.ProjectImporter.importProject(ProjectImporter.java:48)
    at org.ossmeter.platform.client.api.ProjectImportResource.importProject(ProjectImportResource.java:61)
```

The line in question is trying to get the set of platforms that the project supports, and I'm guessing it's null. We should add a null pointer check in here to ensure that this exception does get thrown.

**Comment by jdirocco** [comment]
Bug fixed: I have changed getPlatforms method in EclipseImporter class.
