### ISSUE TITLE
Topics Metric Provider NumberFormatException

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#35]
The exception below was thrown whilst analysing the Acceleo project for the data 20090221.

To reproduce, you can import the project as follows:

``` java
Platform platform = ...
EclipseProjectImporter im = new EclipseProjectImporter();
im.importProjectByUrl("https://projects.eclipse.org/projects/modeling.acceleo", platform);
```

The stack trace:

``` java
ERROR [MetricListExecutor (modeling-acceleo, 20090221)] (03:33:12): Exception thrown during metric provider execution (requestreplyclassification).
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:453)
        at java.lang.Long.parseLong(Long.java:483)
        at java.text.DigitList.getLong(DigitList.java:194)
        at java.text.DecimalFormat.parse(DecimalFormat.java:1316)
        at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2088)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1455)
        at org.ossmeter.platform.communicationchannel.nntp.NntpUtil.parseDate(NntpUtil.java:237)
        at org.ossmeter.metricprovider.trans.topics.TopicsTransMetricProvider.cleanBugTrackers(TopicsTransMetricProvider.java:177)
        at org.ossmeter.metricprovider.trans.topics.TopicsTransMetricProvider.measure(TopicsTransMetricProvider.java:109)
        at org.ossmeter.metricprovider.trans.topics.TopicsTransMetricProvider.measure(TopicsTransMetricProvider.java:1)
        at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by jrwilliams** [comment]
This has also occurred for the Xtext project on date 20100319.

**Comment by yannisKork** [comment]
fixed
