### ISSUE TITLE
SVNManager cannot analyse GitHub repositories

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#38]
For some reason, the SVNManager cannot parse the SVN repos on GitHub. The following exception is thrown:

``` java
org.tmatesoft.svn.core.SVNException: svn: E175002: Processing REPORT request response failed: XML document structures must start and end within the same entity. (/opensourceBIM/BIMserver/!svn/bc/2789) svn: E175002: REPORT request failed on '/opensourceBIM/BIMserver/!svn/bc/2789' at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:106) at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:90) at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:758) at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:371) at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:359) at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:707) at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.doReport(DAVConnection.java:334) at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.doReport(DAVConnection.java:324) at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.logImpl(DAVRepository.java:993) at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:1035) at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:940) at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:864) at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:1412) at org.ossmeter.platform.vcs.svn.SvnManager.getRevisionsForDate(SvnManager.java:185) at org.ossmeter.platform.delta.vcs.PlatformVcsManager.getRevisionsForDate(PlatformVcsManager.java:78) at org.ossmeter.platform.delta.vcs.VcsProjectDelta.(VcsProjectDelta.java:26) at org.ossmeter.platform.delta.ProjectDelta.create(ProjectDelta.java:61) at org.ossmeter.platform.osgi.executors.ProjectExecutor.run(ProjectExecutor.java:127) at org.ossmeter.platform.osgi.executors.SlaveScheduler$2.run(SlaveScheduler.java:109)
```

This can be reproduced easily with the following code:

``` java
public static void main(String[] args) throws Exception {
    SvnRepository svn = new SvnRepository();
    svn.setUrl("https://github.com/ari/jobsworth");

    SvnManager manager = new SvnManager();
    String firstRevision = manager.getFirstRevision(svn);
    System.out.println("first rev: " + firstRevision);
}
```

**Comment by jrwilliams** [comment]
Attempted solution suggested here: http://stackoverflow.com/questions/16414754/svn-processing-report-request-response-failed-the-element-type-meta-must-be 
- Added the VM argument (-Dsvnkit.http.sslProtocols=SSLv3) but it just hung for half an hour.
- Added the inline code: `System.setProperty("svnkit.http.sslProtocols", "SSLv3");` also just hung.

**Comment by kolovos** [comment]
Consensus is that we should not be using the GitHub SVN interface (it only implements a subset of SVN anyway).
