### ISSUE TITLE
Redmine Manager "updated_on" filter causes http 422 error

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#47]
When trying to analyse the Modelio UTP project, the RedmineManager throws an exception. I've narrowed this down to be related to the "updated_on" querystring parameter it creates. It looks like the date string it produces is invalid.

Commenting out line 134 of RedmineRestClient.java (`filter.put("updated_on", dateString);`) removes the error (but potentially introduces other bugs).

The stack trace:

``` java
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Error executing call to webservice. [422,http://forge.modelio.org/issues.json?project_id=utp&status_id=*&updated_on=%3E%3D2012-05-01T23%3A00%3A00Z&offset=0&limit=100]
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineIssueIds$RedmineIssueIdIterator.getNextPage(RedmineIssueIds.java:54)
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineIssueIds$RedmineIssueIdIterator.hasNext(RedmineIssueIds.java:39)
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.getIssues(RedmineRestClient.java:136)
    at org.ossmeter.platform.bugtrackingsystem.redmine.RedmineManager$IssueCacheProvider.getItems(RedmineManager.java:50)
    at org.ossmeter.platform.bugtrackingsystem.cache.Cache.update(Cache.java:69)
    at org.ossmeter.platform.bugtrackingsystem.cache.Cache.getItemsAfterDate(Cache.java:54)
    at org.ossmeter.platform.bugtrackingsystem.redmine.RedmineManager.getDelta(RedmineManager.java:103)
    at org.ossmeter.platform.bugtrackingsystem.redmine.RedmineManager.main(RedmineManager.java:185)
Caused by: java.lang.RuntimeException: Error executing call to webservice. [422,http://forge.modelio.org/issues.json?project_id=utp&status_id=*&updated_on=%3E%3D2012-05-01T23%3A00%3A00Z&offset=0&limit=100]
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.executeRestCall(RedmineRestClient.java:255)
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.search(RedmineRestClient.java:240)
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.basicSearch(RedmineRestClient.java:226)
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.basicSearch(RedmineRestClient.java:220)
    at org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineIssueIds$RedmineIssueIdIterator.getNextPage(RedmineIssueIds.java:52)
    ... 7 more
```

Code to reproduce error (modification of the method at the bottom of RedmineManager.java):

``` java
    public static void main(String[] args) throws Exception {
        RedmineManager manager = new RedmineManager();
        RedmineBugIssueTracker bugTracker = new RedmineBugIssueTracker();
        bugTracker.setUrl("http://forge.modelio.org");
        bugTracker.setProject("utp");
        Date firstDate = manager.getFirstDate(null, bugTracker);
        System.out.println("FIRST DATE: " + firstDate); 

        BugTrackingSystemDelta delta = manager.getDelta(null, bugTracker, firstDate);

        for (BugTrackingSystemBug bug : delta.getNewBugs()) {
            System.out.println(bug.getBugId());
            System.out.println("\""+manager.getContents(null, bugTracker, bug)+"\"");
        }
        manager.shutdown();
    }
```

As an aside, this doesn't affect the UTP project as there is only one bug and so running with the offending line commented out works fine. For projects with multiple bugs, this would cause grief.

**Comment by kolovos** [comment]
Alessandra to provide the exact version of Redmine that forge.modelio.org is running.

**Comment by yannisKork** [comment]
forge.modelio.org does supports this date format YYYY-MM-DD for the updated_on field of the URL. I'll update the manager to use this format if the standard format fails.

**Comment by yannisKork** [comment]
fixed
