### ISSUE TITLE
Web Application not working

### ISSUE THREAD

**Issue by tteixeira** [ossmeter/ossmeter#5]
Tested both v0.1.0 and v0.1.1 releases of the Web Application and we are getting the same error connecting to mongoDB:

---

Play server process ID is 5719
[info] play - Starting application default Akka system.
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
scheduled task is running :)
com.mongodb.MongoException: can't find a master
    at com.mongodb.DBTCPConnector.checkMaster(DBTCPConnector.java:434)
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:209)
    at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:305)
    at com.mongodb.DBCollection.findOne(DBCollection.java:647)
    at com.mongodb.DBCollection.findOne(DBCollection.java:626)
    at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:364)
    at com.mongodb.DBCollection.createIndex(DBCollection.java:436)
    at com.mongodb.DBCollection.ensureIndex(DBCollection.java:515)
    at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
    at model.InvitationRequestCollection.<init>(InvitationRequestCollection.java:11)
    at model.Users.setDb(Users.java:63)
    at model.Users.<init>(Users.java:11)
    at Global$2.run(Global.java:129)
    at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

---

Also tried to run it from source, and its also not working, in this case due an error with the metvis library:

---

[error] /home/ossmeter/ossmeter/web/org-ossmeter-webapp/app/controllers/Admin.java:18: object metvis is not a member of package <root>
[error] import metvis._;
[error]        ^
[error] /home/ossmeter/ossmeter/web/org-ossmeter-webapp/app/controllers/News.java:18: object metvis is not a member of package <root>
[error] import metvis._;
[error]        ^
[error] two errors found

---

We are probably missing some configurations in the mongoDB...

**Comment by jrwilliams** [comment]
We've encountered this issue as well whilst deploying. The problem is that Mongo has trouble resolving DNS names. Try hardcoding the IP address in the application.conf (mongo.host). We got around it by changing /etc/hosts to point our machine name to 127.0.0.1. Other useful info here: http://stackoverflow.com/questions/16592215/connect-to-remote-mongodb-replica-set-when-replica-set-connect-to-each-other-on

**Comment by jrwilliams** [comment]
Will add this to the FAQ.

**Comment by jrwilliams** [comment]
Missing imports fixed in 607d97abe4b7cbb0d2030f6e8d72c43e64599ba0

**Comment by tteixeira** [comment]
Solved in version v0.1.5
