### ISSUE TITLE
Rascal: Control exception from MetricListExecutor: style.styleViolations

### ISSUE THREAD

**Issue by jimmysyl** [ossmeter/ossmeter#59]
The following exception is thrown for the following projects: sonarqube.

``` Java
org.rascalmpl.interpreter.control_exceptions.Throw: rascal://lang::java::style::CheckStates:74,47:
EmptyList() at
org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.j
va:42) at org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:114) at
java.lang.Throwable.(Throwable.java:265) at java.lang.Exception.(Exception.java:66) at
java.lang.RuntimeException.(RuntimeException.java:62) at
org.rascalmpl.interpreter.control_exceptions.ControlException.(ControlException.java:25) at
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:49) at
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:69) at
org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.emptyList(RuntimeExceptionFactory.java:117) at
org.rascalmpl.interpreter.result.ListResult.subscript(ListResult.java:117) at
org.rascalmpl.semantics.dynamic.Expression$Subscript.interpret(Expression.java:2513) at
org.rascalmpl.semantics.dynamic.Expression$FieldAccess.interpret(Expression.java:852) at
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:486) at
org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at
org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at
org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at
org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at
org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at
org.rascalmpl.interpreter.result.AbstractPatternDispatchedFunction.call(AbstractPatternDispatchedFunct
on.java:180) at
org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at
org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at
org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at
org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at
org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at
org.rascalmpl.semantics.dynamic.Statement$For.interpret(Statement.java:467) at
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at 
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at org.rascalmpl.interpreter.utils.Cases.matchAndEval(Cases.java:417) at org.rascalmpl.interpreter.utils.Cases$DefaultBlock.matchAndEval(Cases.java:253) at org.rascalmpl.semantics.dynamic.Statement$Switch.interpret(Statement.java:899) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at org.rascalmpl.semantics.dynamic.Statement$For.interpret(Statement.java:467) at org.rascalmpl.interpreter.utils.Cases.matchAndEval(Cases.java:417) at org.rascalmpl.interpreter.utils.Cases$DefaultBlock.matchAndEval(Cases.java:253) at org.rascalmpl.semantics.dynamic.Statement$Switch.interpret(Statement.java:899) at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at org.rascalmpl.semantics.dynamic.Statement$For.interpret(Statement.java:467) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at org.rascalmpl.semantics.dynamic.Statement$For.interpret(Statement.java:467) at org.rascalmpl.interpreter.utils.Cases.matchAndEval(Cases.java:417) at org.rascalmpl.interpreter.utils.Cases$DefaultBlock.matchAndEval(Cases.java:253) at org.rascalmpl.semantics.dynamic.Statement$Switch.interpret(Statement.java:899) at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at org.rascalmpl.semantics.dynamic.Statement$For.interpret(Statement.java:467) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.interpreter.utils.Cases.matchAndEval(Cases.java:417) at org.rascalmpl.interpreter.utils.Cases$DefaultBlock.matchAndEval(Cases.java:253) at org.rascalmpl.semantics.dynamic.Statement$Switch.interpret(Statement.java:899) at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:758) at org.rascalmpl.semantics.dynamic.Statement$For.interpret(Statement.java:467) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.ListComprehensionWriter.append(ListComprehensionWriter.java:24) at org.rascalmpl.semantics.dynamic.Comprehension.evalComprehension(Comprehension.java:94) at org.rascalmpl.semantics.dynamic.Comprehension$List.interpret(Comprehension.java:38) at org.rascalmpl.semantics.dynamic.Expression$Comprehension.interpret(Expression.java:669) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268) at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302) at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206) at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1) at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
```

**Comment by jurgenvinju** [comment]
@PaulKlint could you review this fix?

**Comment by PaulKlint** [comment]
I am a bit out of touch with this code and I find it hard to assess.

**Comment by jurgenvinju** [comment]
No problem; a question: the code assumed there was always at least one state pushed, but as far as I can assess this is not necessarily so. The fix does not assume this anymore. The only question is whether or not the fix could hide a deeper problem. In any case the current code is more robust so the fix is fine.
