### ISSUE TITLE
Redmine: ProjectExecutor: Delta creation (Error executing call to webservice. [422,http://forge.modelio.org/issues.json?...)

### ISSUE THREAD

**Issue by jimmysyl** [ossmeter/ossmeter#61]
The following exception was thrown for the following project: UTP

``` Java
java.lang.RuntimeException: java.lang.RuntimeException: Error executing call to webservice.
[422,http://forge.modelio.org/issues.json?project_id=utp&status_id=*&updated_on=%3E%3D2015-02
27T00%3A00%3A00Z&offset=0&limit=100] at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineIssueIds$RedmineIssueIdIterator.getNex
Page(RedmineIssueIds.java:54) at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineIssueIds$RedmineIssueIdIterator.hasNe
t(RedmineIssueIds.java:39) at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.getIssues(RedmineRestClient
java:136) at
org.ossmeter.platform.bugtrackingsystem.redmine.RedmineManager$IssueCacheProvider.getItems(Re
mineManager.java:50) at org.ossmeter.platform.bugtrackingsystem.cache.Cache.update(Cache.java:69)
at org.ossmeter.platform.bugtrackingsystem.cache.Cache.getItemsAfterDate(Cache.java:54) at
org.ossmeter.platform.bugtrackingsystem.redmine.RedmineManager.getDelta(RedmineManager.java:1
3) at
org.ossmeter.platform.bugtrackingsystem.redmine.RedmineManager.getDelta(RedmineManager.java:1)
at
org.ossmeter.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(Platform
ugTrackingSystemManager.java:101) at
org.ossmeter.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta
(BugTrackingSystemProjectDelta.java:33) at
org.ossmeter.platform.delta.ProjectDelta.create(ProjectDelta.java:70) at
org.ossmeter.platform.osgi.executors.ProjectExecutor.run(ProjectExecutor.java:127) at
org.ossmeter.platform.osgi.executors.SlaveScheduler$2.run(SlaveScheduler.java:109) Caused by:
java.lang.RuntimeException: Error executing call to webservice.
[422,http://forge.modelio.org/issues.json?project_id=utp&status_id=*&updated_on=%3E%3D2015-02
27T00%3A00%3A00Z&offset=0&limit=100] at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.executeRestCall(RedmineRe
tClient.java:255) at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.search(RedmineRestClient.ja
a:240) at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.basicSearch(RedmineRestCl
ent.java:226) at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineRestClient.basicSearch(RedmineRestCl
ent.java:220) at
org.ossmeter.platform.bugtrackingsystem.redmine.api.RedmineIssueIds$RedmineIssueIdIterator.getNex
Page(RedmineIssueIds.java:52) ... 12 more
```

**Comment by yannisKork** [comment]
This is the same issue as issue 47: https://github.com/ossmeter/ossmeter/issues/47
Closing as duplicate.
