### ISSUE TITLE
Rascal: licenses metric provider IndexOutOfBounds exception

### ISSUE THREAD

**Issue by nmatra** [ossmeter/ossmeter#77]
Got the following exception while running the platform on [pongo](https://code.google.com/p/pongo/).
Date: 20130201
Project: pongo

Any ideas?

``` Java
ERROR [RascalMetricProvider (Used licenses (from selected list of known licenses))] (14:31:27): metric threw an exception: rascal://Comments:442,59: IndexOutOfBounds(255) at |rascal://Comments|(20117,10,<442,59>,<442,69>)
org.rascalmpl.interpreter.control_exceptions.Throw: rascal://Comments:442,59: IndexOutOfBounds(255)
    at org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.java:42)
    at org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:114)
    at java.lang.Throwable.<init>(Throwable.java:265)
    at java.lang.Exception.<init>(Exception.java:66)
    at java.lang.RuntimeException.<init>(RuntimeException.java:62)
    at org.rascalmpl.interpreter.control_exceptions.ControlException.<init>(ControlException.java:25)
    at org.rascalmpl.interpreter.control_exceptions.Throw.<init>(Throw.java:49)
    at org.rascalmpl.interpreter.control_exceptions.Throw.<init>(Throw.java:69)
    at org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.indexOutOfBounds(RuntimeExceptionFactory.java:143)
    at org.rascalmpl.interpreter.result.ElementResult.slice(ElementResult.java:271)
    at org.rascalmpl.interpreter.result.ListOrRelationResult.slice(ListOrRelationResult.java:44)
    at org.rascalmpl.semantics.dynamic.Expression$Slice.interpret(Expression.java:2451)
    at org.rascalmpl.interpreter.matching.EnumeratorResult.next(EnumeratorResult.java:70)
    at org.rascalmpl.semantics.dynamic.Comprehension.evalComprehension(Comprehension.java:92)
    at org.rascalmpl.semantics.dynamic.Comprehension$Set.interpret(Comprehension.java:70)
    at org.rascalmpl.semantics.dynamic.Expression$Comprehension.interpret(Expression.java:669)
    at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364)
    at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782)
    at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349)
    at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295)
    at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359)
    at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337)
    at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524)
    at org.rascalmpl.semantics.dynamic.MapComprehensionWriter.append(MapComprehensionWriter.java:26)
    at org.rascalmpl.semantics.dynamic.Comprehension.evalComprehension(Comprehension.java:94)
    at org.rascalmpl.semantics.dynamic.Comprehension$Map.interpret(Comprehension.java:56)
    at org.rascalmpl.semantics.dynamic.Expression$Comprehension.interpret(Expression.java:669)
    at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364)
    at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204)
    at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349)
    at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
    at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR [RascalMetricProvider (Used licenses (from selected list of known licenses))] (14:31:27):     at extractHeader(:442,8)
    at matchingLicenses(:520,79)
    at ******ossmeter******(:)
```

**Comment by ashimshahi** [comment]
4ee388e45258d7ff5681c9934411503ae6ad366a should have fixed this issue.

Is the source not up to date by any chance?

**Comment by nmatra** [comment]
You are right. It is fine now. Thanks
