### ISSUE TITLE
organization metric fails because author meta data is not storing email addresses

### ISSUE THREAD

**Issue by jurgenvinju** [ossmeter/ossmeter#90]
Márcio reported the following:

```
We are having a problem with the metric used to determine the domain of the committers that you develop for us. We ran some tests using different projects from both Github and SourceForge but the metric developmentDomainNames never produced any result. Its collection in mongodb is always empty. 

By looking into the code we saw that this metric uses another metric called developmentTeam. This one is working as all the committers seem to be listed under its collection. However this metric is only storing the name of each committer. Wasn’t it also supposed to store committers’ email address?

We are currently running the vanillaproduct with only your metrics (and some dependences that were needed) but when we ran all metrics (using ossmeterfromfeature.product) we got the same results.
```

The cause is that the author identification information string in our meta data for VcsCommit is not an email address anymore, but its the name as configured with git. Any metric that depends on names thus has not the right information.

@nmatra @jrwilliams @kolovos @davidediruscio, guys: we can add an email field to the VcsCommit data easily for git and not for svn. Then I can duplicate some of the metrics to be based on email addresses instead of names. Do or don't? I don't think it would make the system unstable as far as I can see.

**Comment by nmatra** [comment]
I do not think that such a change is crucial at this point but I agree that the system will not become unstable by it.

**Comment by MarcioMateus** [comment]
I'm glad that this change is not a problem.

We (Unparallel Innovation) require this change to identify potential users of Construction projects and resume the Usage assessment.

**Comment by jurgenvinju** [comment]
@MarcioMateus could you test the new feature? I've added the meta information and new metrics to fix this issue: developmentDomainNames is now depending on the new developmentTeamEmails which depends on the new committersEmailsToday which uses the information from git on email addresses of the developers. Svn repositories do not do anything useful here.

**Comment by MarcioMateus** [comment]
@jurgenvinju, I did tested the new feature and I got the following exception for Assimp:

```
ERROR [RascalMetricProvider (Development team)] (15:19:56): a static error in a Rascal function was detected
org.rascalmpl.interpreter.staticErrors.UnsupportedOperation: addition not supported on set[void] and set[str] (...)
[Advice](http://tutor.rascal-mpl.org/Errors/Static/UnsupportedOperation/UnsupportedOperation.html)
    at ActiveCommitters.?(:103)
    at org.rascalmpl.interpreter.result.Result.undefinedError(Result.java:188)
    at org.rascalmpl.interpreter.result.Result.addRelation(Result.java:411)
    at org.rascalmpl.interpreter.result.RelationResult.add(RelationResult.java:51)
    at org.rascalmpl.semantics.dynamic.Expression$Addition.interpret(Expression.java:135)
    at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364)
    at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782)
    at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349)
    at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
    at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR [MetricListExecutor (assimp, 20080505)] (15:19:56): Exception thrown during metric provider execution (developmentTeamEmails).
org.rascalmpl.interpreter.staticErrors.UnsupportedOperation: addition not supported on set[void] and set[str] (...)
[Advice](http://tutor.rascal-mpl.org/Errors/Static/UnsupportedOperation/UnsupportedOperation.html)
    at ActiveCommitters.?(:103)
    at org.rascalmpl.interpreter.result.Result.undefinedError(Result.java:188)
    at org.rascalmpl.interpreter.result.Result.addRelation(Result.java:411)
    at org.rascalmpl.interpreter.result.RelationResult.add(RelationResult.java:51)
    at org.rascalmpl.semantics.dynamic.Expression$Addition.interpret(Expression.java:135)
    at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364)
    at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782)
    at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349)
    at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
    at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
WARN  [ProjectExecutor (assimp)] (15:19:56): Project in error state. Stopping execution.
INFO  [ProjectExecutor (assimp)] (15:19:56): Project execution complete. In error state: true
```

I tried to reset Assip's database but I still got the same exception. After that I tried with other projects in my database and got the same results. As this exception could be caused by an incomplete reset of the projects' database I decided to add a now project and still got the same exception.

**Comment by jurgenvinju** [comment]
o wow. That slipped through; will fix

**Comment by jurgenvinju** [comment]
that should help. please try again and thanks for your patience

**Comment by MarcioMateus** [comment]
That exception is solved, but now I get another one:

```
ERROR [RascalMetricProvider (Development team domain names)] (17:29:03): a static error in a Rascal function was detected
org.rascalmpl.interpreter.staticErrors.NotEnumerable: set[str] (...) is not enumerable
[Advice](http://tutor.rascal-mpl.org/Errors/Static/NotEnumerable/NotEnumerable.html)
    at ActiveCommitters.?(:113)
    at org.rascalmpl.interpreter.matching.IteratorFactory.elementType(IteratorFactory.java:61)
    at org.rascalmpl.interpreter.matching.EnumeratorResult.next(EnumeratorResult.java:71)
    at org.rascalmpl.semantics.dynamic.Comprehension.evalComprehension(Comprehension.java:92)
    at org.rascalmpl.semantics.dynamic.Comprehension$Set.interpret(Comprehension.java:70)
    at org.rascalmpl.semantics.dynamic.Expression$Comprehension.interpret(Expression.java:669)
    at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364)
    at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782)
    at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349)
    at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
    at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR [MetricListExecutor (writegood, 20140425)] (17:29:03): Exception thrown during metric provider execution (developmentDomainNames).
org.rascalmpl.interpreter.staticErrors.NotEnumerable: set[str] (...) is not enumerable
[Advice](http://tutor.rascal-mpl.org/Errors/Static/NotEnumerable/NotEnumerable.html)
    at ActiveCommitters.?(:113)
    at org.rascalmpl.interpreter.matching.IteratorFactory.elementType(IteratorFactory.java:61)
    at org.rascalmpl.interpreter.matching.EnumeratorResult.next(EnumeratorResult.java:71)
    at org.rascalmpl.semantics.dynamic.Comprehension.evalComprehension(Comprehension.java:92)
    at org.rascalmpl.semantics.dynamic.Comprehension$Set.interpret(Comprehension.java:70)
    at org.rascalmpl.semantics.dynamic.Expression$Comprehension.interpret(Expression.java:669)
    at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364)
    at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782)
    at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349)
    at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206)
    at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
    at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
WARN  [ProjectExecutor (write-good)] (17:29:03): Project in error state. Stopping execution.
INFO  [ProjectExecutor (write-good)] (17:29:03): Project execution complete. In error state: true
```

I got the same exception in all projects.

**Comment by jurgenvinju** [comment]
Hi @MarcioMateus, sorry for that. I can't easily check the code because my Eclipse environment is messed up now so I am doing these "easy fixes" by heart. Should work now.

**Comment by MarcioMateus** [comment]
No problem @jurgenvinju. I also have some messed up Eclipse environments in my VM and I'm not developing like you guys.

After this fix I no longer get any exception. However, i think that the metric isn't getting the email address right. I'm running the project Assimp and there are already some documents inside the developmentTeamEmails collection, but the email addresses are all in the format "user@67173fc5-114c-0410-ac8e-9d2fd5bffc1f" (e.g. "aramis_acg@67173fc5-114c-0410-ac8e-9d2fd5bffc1f", "marksibly@67173fc5-114c-0410-ac8e-9d2fd5bffc1f", ...). As result, collection developmentDomainNames has only one domain: "67173fc5-114c-0410-ac8e-9d2fd5bffc1f".

**Comment by jurgenvinju** [comment]
now that is an interesting one. I will look into that tomorrow morning. Have you tried on other projects as well by any chance?

**Comment by MarcioMateus** [comment]
I tried on write-good project, which is smaller and more recent and the metric worked fine.

The problem with Assimp may be related with the age of the commits (2008-2009) and the platform isn´t able to accurately identify the email address of the committers. I will let to Assimp run until more recent dates to see if OSSMETER starts getting the information right.

**Comment by jurgenvinju** [comment]
Thanks Marcio. For now can we consider this bug closed?

**Comment by MarcioMateus** [comment]
Yes, since email addresses related with more recent commits seems to be correct. Thank you for the help.
